version: "3"
services:
  postgresnode:
    environment:
      - POSTGRES_USER=express
      - POSTGRES_PASSWORD=express
      - POSTGRES_DB=express
    container_name: postgresnode
    image: "postgres:15.0"
    ports:
      - "5432:5432"
  backend:
    container_name: nodeapibackend
    build: ./backend
    image: nodeapibackend:v1
    ports:
      - "5002:5002"
    depends_on:
      - "postgresnode"

#cd nodeapi
#docker compose build
#docker compose up --attach backend